collections:
  - name: blog
    label: Blog
    folder: src/content/blog
    format: markdown
    create: true
    slug: "{{year}}-{{month}}-{{slug}}"
    fields:
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: string
      - name: date
        label: Date
        type: date
      - name: image
        label: Image
        type: string
        required: false
      - name: category
        label: Category
        type: string
        required: false
      - name: tags
        label: Tags
        type: list
        field:
          type: string
      - name: draft
        label: Draft
        type: boolean
        required: false
      - name: body
        label: Body
        type: markdown

  - name: projects
    label: Projects
    folder: src/content/projects
    format: markdown
    create: true
    slug: "{{slug}}"
    fields:
      - name: title
        label: Title
        type: string
      - name: summary
        label: Summary
        type: string
      - name: date
        label: Date
        type: date
      - name: tags
        label: Tags
        type: list
        field:
          type: string
      - name: image
        label: Image
        type: string
        required: false
      - name: technologies
        label: Technologies
        type: list
        field:
          type: string
        required: false
      - name: liveUrl
        label: Live URL
        type: string
        required: false
      - name: repoUrl
        label: Repository URL
        type: string
        required: false
      - name: demoUrl
        label: Demo URL
        type: string
        required: false
      - name: draft
        label: Draft
        type: boolean
        required: false
      - name: body
        label: Body
        type: markdown
    
    - name: projects
	label: Projects
	type: collection
    path: src/content/projects
    view:
      fields: [ title, draft, date ]
    fields:
      - { name: author, label: Author, type: string }
      - { name: pubDatetime, label: Date, type: date }
      - { name: modDatetime, label: Date, type: date }
      - { name: title, label: Title, type: string, required: true }
      - { name: ogImage, label: Title, type: string }
      - { name: slug, label: Slug, type: string }
      - { name: featured, label: Featured, type: boolean }
      - { name: draft, label: Draft, type: boolean }
      - { name: tags, label: Tags, type: string, list: true }
      - { name: description, label: Description, type: string }
      - { name: body, label: Body, type: rich-text }
      
  - name: about
    label: About page
    type: file
    path: src/pages/about
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
      
  - name: projects
    label: Projects page
    type: file
    path: src/pages/projects
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
      
   - name: terms
    label: Terms page
    type: file
    path: src/pages/terms
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
      
      - name: privacy
    label: Privacy page
    type: file
    path: src/pages/privacy
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
      - name: about
    label: About page
    type: file
    path: src/pages/about/index.astro
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
  - name: projects
    label: Projects page
    type: file
    path: src/pages/projects/index.astro
    fields:
      - { name: layout, type: string, hidden: true, default: "../layouts/Layout.astro" }
      - { name: title, label: Title, type: string }
      - { name: body, label: Body, type: rich-text, options: { input: public/assets, output: /assets } }
