export default {
  name: 'posts',
  label: 'Posts',
  folder: 'content/posts',
  extension: 'md',
  fields: [
    { name: 'title', label: 'Title', widget: 'string' },
    { name: 'slug', label: 'Slug', widget: 'string' },
    { name: 'cover', label: 'Cover Image', widget: 'image' },
    { name: 'tags', label: 'Tags', widget: 'list' },
    { name: 'category', label: 'Category', widget: 'string' },
    { name: 'seo', label: 'SEO Meta', widget: 'object', fields: [
      { name: 'title', widget: 'string' },
      { name: 'description', widget: 'text' },
    ]},
    { name: 'content', label: 'Content', widget: 'markdown' },
  ]
}
